### ISSUE TITLE
__cap_relocs emitted with sh_addralign=1

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/llvm#128]
The `__cap_reallocs` section is being emitted under-aligned.  For simple programs it doesn't matter much and often seems to end up correctly aligned, but in `tcpdump-helper` it ends up misaligned which I believe is one contributor to sandbox initialization taking much longer with `-cheri-linker` (over a minute)

elfdump -a output from tcpdump-helper:
```
entry: 7
        sh_name: __cap_relocs
        sh_type: SHT_PROGBITS
        sh_flags: 
        sh_addr: 0x18037b
        sh_offset: 1573755
        sh_size: 311320
        sh_link: 0
        sh_info: 0
        sh_addralign: 1
        sh_entsize: 0
```

Also from print-ether.o:
```
entry: 13
        sh_name: __cap_relocs
        sh_type: SHT_PROGBITS
        sh_flags: 
        sh_addr: 0
        sh_offset: 9244
        sh_size: 2000
        sh_link: 0
        sh_info: 0
        sh_addralign: 1
        sh_entsize: 0
```
